default:
  tags:
    - backend-docker

stages:
  - build
  - publish

build:
  stage: build
  image: gradle:jdk21-jammy
  script:
    - gradle build --no-daemon -x test

publish:
  stage: publish
  image: gradle:jdk21-jammy
  only:
    - main
  script:
    - gradle publishMavenPublicationToGitLabRepository --no-daemon
