package kz.rmr.chatmachinist_mongo.repository

import kz.rmr.chatmachinist_mongo.document.UpdateResponseDocument
import org.springframework.data.mongodb.repository.MongoRepository

interface UpdateResponseDocumentRepository: MongoRepository<UpdateResponseDocument, String>